### ISSUE TITLE
Add options to configure SVGO

### ISSUE THREAD

**Issue by yesyo** [asnowwolf/markup-inline-loader#5]
I have to disable some of the SVGO default config options. It would be great if you can support this. Thanks for the great work.

**Comment by boschr** [comment]
[I just pushed this feature](https://github.com/asnowwolf/markup-inline-loader/pull/7). Waiting for @asnowwolf to approve the PR.

**Comment by yesyo** [comment]
@boschr Cool! Thanks.

**Comment by asnowwolf** [comment]
Great, thank you! I've add some comments on that PR.
